name: mle
channels:  
  - anaconda
  
dependencies:
  - python=3.8
  - bokeh
  - cloudpickle
  - graphviz
  - joblib
  - jupyterlab
  - keras
  - llvmlite
  - nltk 
  - numba
  - networkx
  - pandas  
  - pydot
  - requests  
  - scikit-learn  
  - seaborn  
  - statsmodels
  - sympy  
  - tqdm     
  - pip:
    - econml
    
      